Test refactoring /cc @arturi @hedgerh
- Move failing multipart dir into a v0.0.5 directory
- Add a passing dummy i18n acceptance test
- Move acceptance tests into own dir, just like unit tests
- Make acceptance test run the same way as as unit tests, via an
index.js
- Remove bash requirement to run acceptance tests

diff --git a/bin/bootandkill-servers b/bin/bootandkill-servers
--- a/bin/bootandkill-servers
+++ b/bin/bootandkill-servers
@@ -44,6 +44,22 @@ function cleanup_servers () {
   kill -9 ${tailPid}
 }
 
+function waitForPortOpen () {
+  local port="${1}"
+  local limit="${2:-60}"
+  local attempts=0
+  echo "[${__base}] waiting on port ${port} to open... "
+  while ! echo exit | nc localhost ${port}; do
+    let "attempts = attempts + 1"
+    echo "[${__base}] still waiting on port ${port} to open... (${attempts} / ${limit}) "
+    sleep 1
+    if [ "${attempts}" -ge "${limit}" ]; then
+      echo "[${__base}] --> Port did not open for ${limit} seconds. Aborting. "
+      exit 1
+    fi
+  done
+}
+
 echo "[${__base}] --> Killing any server listening on port 4000"
 killProcessListeningOnPort 4000 || true
 echo "[${__base}] --> Killing any server listening on port 8080"
@@ -57,6 +73,17 @@ tail -f nohup.out &
 tailPid=${!}
 
 trap cleanup_servers EXIT
+
+
+
+echo "[${__base}] --> Wait for hexo webserver to be online"
+waitForPortOpen 4000
+
+echo "[${__base}] --> Wait for uppy-server to be online"
+waitForPortOpen 8080
+
+echo "[${__base}] --> Running acceptance tests"
+
 
 echo "[${__base}] --> Sleeping 20s, because the port may be open, but Hexo may still be injecting/building stuff"
 echo "[${__base}] --> and I don't know yet how to check for that"
